# Generated by Django 4.2.1 on 2023-06-09 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Cantidad_Productos', models.CharField(max_length=50)),
                ('Valor', models.IntegerField()),
                ('Descripción', models.CharField(max_length=70)),
            ],
        ),
    ]
