# Generated by Django 4.2.2 on 2023-08-11 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Productos', '0003_rename_descripcion_productos_descripcion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productos',
            name='estado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='productos',
            name='nombre',
            field=models.CharField(default='', max_length=50),
        ),
    ]
