# Generated by Django 4.2.2 on 2023-08-11 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0002_empleados_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleados',
            name='telefono',
            field=models.BigIntegerField(),
        ),
    ]
