# Generated by Django 4.2.2 on 2023-06-28 23:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0002_solicitud'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Solicitud',
        ),
    ]
