# Generated by Django 4.2.2 on 2023-09-19 14:23

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cmp', '0002_ventasenc_ventasdet'),
    ]

    operations = [
        migrations.AddField(
            model_name='ventasdet',
            name='venta',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='cmp.ventasenc'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ventasenc',
            name='fecha_venta',
            field=models.DateField(blank=True, null=True),
        ),
    ]
