# Generated by Django 4.2.2 on 2023-08-15 19:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0006_cliente_estado'),
        ('venta', '0002_alter_cliente_telefono'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cliente.cliente'),
        ),
        migrations.DeleteModel(
            name='Cliente',
        ),
    ]
