# Generated by Django 4.2.2 on 2023-09-15 00:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('venta', '0004_alter_venta_options_venta_estado_venta_fc_venta_fm_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='venta',
            options={},
        ),
        migrations.RemoveField(
            model_name='venta',
            name='estado',
        ),
    ]
