# Generated by Django 4.2.2 on 2023-09-17 01:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('venta', '0006_ventaenc_ventadet'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ventaenc',
            name='productos',
        ),
        migrations.RemoveField(
            model_name='ventaenc',
            name='uc',
        ),
        migrations.DeleteModel(
            name='VentaDet',
        ),
        migrations.DeleteModel(
            name='VentaEnc',
        ),
    ]
